
set(proj ITK)

set(ITK_DIR ${CMAKE_BINARY_DIR}/${proj}-build)

ExternalProject_Add(${proj}
  GIT_REPOSITORY git://itk.org/ITK.git
  GIT_TAG v4.0.0
  SOURCE_DIR ${proj}
  BINARY_DIR ${ITK_DIR}
  UPDATE_COMMAND ""
  INSTALL_COMMAND ""
  CMAKE_ARGS
  ${${CMAKE_PROJECT_NAME}_SUPERBUILD_EP_ARGS}
  -DBUILD_EXAMPLES:BOOL=OFF
  -DBUILD_TESTING:BOOL=OFF
  -DITK_LEGACY_REMOVE:BOOL=ON
  -DITK_BUILD_ALL_MODULES:BOOL=ON
  )
