#pragma once
// 
#include <vector>

//qt
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QStatusBar>
#include <QLabel>
#include <QString>
#include <QFileDialog>
#include <QColorDialog>
#include <QPushButton>
#include <QColor>

//vtk
#include <vtkSTLreader.h>
#include <vtkSTLWriter.h>
#include <vtkPolyDataMapper.h>
#include <vtkActor.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkSmartPointer.h>
#include <vtkCamera.h>
#include <vtkAssembly.h>
#include <vtkFloatArray.h>
#include <vtkPointData.h>
#include <vtkProperty.h>
#include <vtkEventQtSlotConnect.h>
#include <vtkInteractorStyleTrackballActor.h>
#include <vtkCubeAxesActor.h>
#include <vtkMatrix4x4.h>
#include <vtkCellPicker.h>
#include <vtkPropCollection.h>
#include <vtkImageActor.h>
#include <vtkImageData.h>
#include <vtkPolyDataToImageStencil.h>
#include <vtkImageStencil.h>
#include <vtkBMPWriter.h>
#include <vtkPlane.h>
#include <vtkCutter.h>
#include <vtkNamedColors.h>
#include <vtkStripper.h>
#include <vtkLinearExtrusionFilter.h>
#include <vtkAxesActor.h>
#include <vtkCaptionActor2D.h>
#include <vtkActorCollection.h>
#include <vtkCommand.h>
#include <vtkTextProperty.h>
#include <vtkTextActor.h>
#include <vtkAppendPolyData.h>
#include <vtkImageResize.h>
#include <vtkImageCanvasSource2D.h>
#include <vtkTransform.h>
#include <vtkTransformPolyDataFilter.h>
#include <vtkLineSource.h>
#include <vtkFeatureEdges.h>
#include <vtkCleanPolyData.h>
#include <vtkCellArray.h>
#include <vtkQImageToImageSource.h>
#include <vtkRendererCollection.h>
#include <vtkOutputWindow.h>
#include <vtkBooleanOperationPolyDataFilter.h>
#include <vtkPolyDataNormals.h>
#include <vtkFillHolesFilter.h>
#include <vtkQuadricDecimation.h>
#include <vtkTriangleFilter.h>
#include <vtkInteractorObserver.h>
#include <vtkCleanPolyData.h>
#include <vtkImplicitPolyDataDistance.h>
#include <vtkContourFilter.h>
#include <vtkDepthSortPolyData.h>
#include <vtkLookupTable.h>
#include <vtkDoubleArray.h>
#include <vtkScalarBarActor.h>
#include <vtkColorSeries.h>
#include <vtkSphereSource.h>
#include <vtkNew.h>
#include <vtkCellData.h>
#include <vtkImplicitModeller.h>
#include <vtkImageActor.h>